version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies
      - yum install -y httpd
  build:
    commands:
      - echo Building the application
  post_build:
    commands:
      - echo Deployment complete
artifacts:
  files:
    - '**/*'
